---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-division-division-io-v1-divideresource
  failurePolicy: Fail
  name: vdivideresource.kb.io
  rules:
  - apiGroups:
    - division.division.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - divideresources
  sideEffects: None
