---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - division.division.io
  resources:
  - divideresources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - division.division.io
  resources:
  - divideresources/finalizers
  verbs:
  - update
- apiGroups:
  - division.division.io
  resources:
  - divideresources/status
  verbs:
  - get
  - patch
  - update
